### ISSUE TITLE
Wrong data in the fixtures folder

### ISSUE THREAD

**Issue by tonicebrian** [FUB-HCC/neonion#101]
When following instructions for installing the software the step of data loading fails with:

```
python manage.py loaddata fixtures/*
Traceback (most recent call last):
  File "manage.py", line 18, in <module>
    execute_from_command_line(sys.argv)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 90, in loaddata
    self.load_label(fixture_label)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 147, in load_label
    obj.save(using=self.using)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/core/serializers/base.py", line 173, in save
    models.Model.save_base(self.object, using=using, raw=True)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 738, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 803, in _save_table
    forced_update)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/db/models/base.py", line 853, in _do_update
    return filtered._update(values) > 0
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/db/models/query.py", line 580, in _update
    return query.get_compiler(self.db).execute_sql(CURSOR)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 1048, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 829, in execute_sql
    cursor.execute(sql, params)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/cebrian/GIT/neonion/pyenv/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 318, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: Problem installing fixture '/home/cebrian/GIT/neonion/fixtures/documents.json': Could not load documents.Document(pk=688cea47c27f11e494e4c42c0303b893): no such column: concept_set_id
```

seems like there is an incompatibility between the jsons and the SQL schema.

**Comment by mackeprm** [comment]
while running this, i had to change the code in the migration from 
```
('concept_set', models.ForeignKey(on_delete=django.db.models.deletion.SET_DEFAULT, default="default", to='annotationsets.ConceptSet'))
```
to:
```
        migrations.AddField(
            model_name='document',
            name='concept_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.SET_DEFAULT, default="default",
                                    to='annotationsets.ConceptSet'),
        ),
```

Maybe possible issue?
